version: "3"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_DIR}/wireguard:/config
    ports:
      - 51820:51820/udp
      # Services that use wireguard need their web GUI ports exposing here
      - ${PORT_FIREFOX}:3000
      - ${PORT_SLSKD_HTTP}:5030
      - ${PORT_SLSKD_LISTEN}:50300
      - ${PORT_THELOUNGE}:9000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
