#!/bin/sh

program="docker-compose"

which podman-compose > /dev/null
if [ $? = 0 ]; then
    program="podman-compose"
fi

${program} --env-file config.env -f $(pwd)/services/${1}/docker-compose.yml down
