version: "3"

services:
  picard:
    image: docker.io/mikenye/picard:2.12.3
    container_name: picard
    restart: unless-stopped
    ports:
      - ${PORT_PICARD}:5800
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/picard:/config
      - ${DOWNLOADS_DIR}:/storage
