version: "3"

services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    restart: unless-stopped
    ports:
      - ${PORT_KAVITA}:5000
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/kavita:/kavita/config
      - ${EBOOK_DIR}:/ebooks:ro
