version: "3"

services:
  watchyourlan:
    image: docker.io/aceberg/watchyourlan:v2
    container_name: watchyourlan
    restart: always
    network_mode: host
    environment:
      TZ: ${TZ}
      IFACES: ${WATCHYOURLAN_NETWORK_INTERFACE}
      PORT: ${PORT_WATCHYOURLAN}
    volumes:
      - ${CONFIG_DIR}/watchyourlan:/data/WatchYourLAN
