version: "3"

services:
  metube:
    image: docker.io/alexta69/metube
    container_name: metube
    restart: always
    ports:
      - ${PORT_METUBE}:8081
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${YOUTUBE_DIR}:/downloads
