version: "3"

services:
  slskd:
    image: docker.io/slskd/slskd
    container_name: slskd
    restart: unless-stopped
    network_mode: "container:wireguard"
    user: ${PUID}:${PGID}
    environment:
      TZ: ${TZ}
      SLSKD_REMOTE_CONFIGURATION: "true"
    volumes:
      - ${CONFIG_DIR}/slskd:/app
      - ${DOWNLOADS_DIR}:/downloads
      - ${AUDIO_DIR}:/media/audio:ro
      - ${AUDIOBOOK_DIR}:/media/audiobooks:ro
      - ${EBOOK_DIR}:/media/ebooks:ro
      - ${PODCASTS_DIR}:/media/podcasts:ro
      - ${RADIO_DIR}:/media/radio:ro
      - ${YOUTUBE_DIR}:/media/youtube:ro
