version: "3"

services:
  redlib:
    image: quay.io/redlib/redlib:latest
    container_name: redlib
    restart: always
    user: nobody
    cap_drop:
      - ALL
    ports:
      - ${PORT_REDLIB}:8080
    environment:
      TZ: ${TZ}
      REDLIB_DEFAULT_LAYOUT: compact
      REDLIB_DEFAULT_SHOW_NSFW: "on"
      REDLIB_DEFAULT_USE_HLS: "on"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
