version: "3"

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    ports:
      - ${PORT_EXCALIDRAW}:80
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
