version: "3"

services:
  syncthing:
    image: docker.io/syncthing/syncthing
    container_name: syncthing
    restart: always
    network_mode: host
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/syncthing/config:/var/syncthing/config
      - ${SYNC_PHONE_DIR}:/var/syncthing/sync-phone
      - ${SYNC_PHONE_DCIM_DIR}:/var/syncthing/sync-phone-dcim
      - ${SYNC_PHONE_GPX_DIR}:/var/syncthing/sync-phone-gpx
      - ${SYNC_SERVER_DIR}:/var/syncthing/sync-server
