version: "3"

services:
  circles:
    image: circles
    container_name: circles
    restart: always
    ports:
      - ${PORT_CIRCLES}:8080
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/circles:/data
