version: "3"

services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - ${PORT_ITTOOLS}:80
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
