version: "3"

services:
  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - ${PORT_GITEA_HTTP}:3000
      - ${PORT_GITEA_SSH}:22
    environment:
      USER_UID: ${PUID}
      USER_GID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
