version: "3"

services:
  navidrome:
    image: docker.io/deluan/navidrome:latest
    container_name: navidrome
    restart: always
    ports:
      - ${PORT_NAVIDROME}:4533
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      ND_LOGLEVEL: info
    volumes:
      - ${CONFIG_DIR}/navidrome:/data
      - ${MUSIC_DIR}:/music:ro
