version: "3"

services:
  stump:
    image: docker.io/aaronleopold/stump:nightly
    container_name: stump
    restart: always
    ports:
      - ${PORT_STUMP}:10801
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SESSION_TTL: 31536000
    volumes:
      - ${CONFIG_DIR}/stump:/config
      - ${EBOOK_DIR}:/data
