version: "3"

services:
  photofield:
    image: ghcr.io/smilyorg/photofield
    container_name: photofield
    restart: always
    ports:
      - ${PORT_PHOTOFIELD}:8080
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/photofield:/app/data
      - ${PHOTOS_DIR}:/app/photo:ro
