version: "3"

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    ports:
      - ${PORT_CALIBRE_DESKTOP_GUI}:8080
      - ${PORT_CALIBRE_WEBSERVER_GUI}:8081
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/calibre:/config
      - ${EBOOK_DIR}:/ebooks
