version: "3"

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.9.0
    container_name: mealie
    restart: unless-stopped
    ports:
      - ${PORT_MEALIE}:9000
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      ALLOW_SIGNUP: "true"
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      #BASE_URL: https://mealie.yourdomain.com
    volumes:
      - ${CONFIG_DIR}/mealie:/app/data
